### ISSUE TITLE
fast_mpc crashes matlab

### ISSUE THREAD

**Issue by jywang2016** [cvxgrp/osc#1]
The fast mpc library can be successfully compiled. However, the given examples will crash MATLAB,  as described in this [post](https://ww2.mathworks.cn/matlabcentral/answers/308688-unable-to-compile-using-mex-fmpc_sim-c-libmwblas-lib-libmwlapack-lib-undefined-reference-to-_dgem). Is it caused by the OS since I use windows 10 to reproduce it?

**Comment by bodono** [comment]
This is the OSC project, for fast_mpc problems you should contact the original authors of that project.

https://stanford.edu/~boyd/fast_mpc/
